### ISSUE TITLE
安装配置后没反应？

### ISSUE THREAD

**Issue by callmesoul** [hezzze/strapi-provider-upload-oss#14]
Strapi v3.6.2
安装成功了，也配置了config/plugins.js

但启动后没有什么变化的？
重新打包了也不行

**Comment by callmesoul** [comment]
试下了上传是可以的

**Comment by hezzze** [comment]
@callmesoul  你说变化是啥？需要配置config/plugins.js 后就可以用media library 上传了，会自动传到阿里云

**Comment by callmesoul** [comment]
我以为是有个配置界面之类的，像你这张图
[img](https://user-images.githubusercontent.com/2413682/63400602-fc1b3480-c406-11e9-91c6-db11c7c2ba67.png)

**Comment by hezzze** [comment]
@callmesoul 这个是Beta版本才有的，新版本把这个界面去掉了
