### ISSUE TITLE
无法在不上传文件的情况下确认插件是否加载成功

### ISSUE THREAD

**Issue by DevDengChao** [hezzze/strapi-provider-upload-oss#20]
目前按照文档上的要求写好 ./config/plugins.js 文件后启动应用, 在控制台的 General > Plugins 里看不到已加载的阿里云 OSS 上传插件. 必须要手动上传一次才知道插件已经加载好了.

**Comment by hezzze** [comment]
插件加载状态应该目前是没有显示的
