### ISSUE TITLE
配置问题与权限问题

### ISSUE THREAD

**Issue by fakecode0** [hezzze/strapi-provider-upload-oss#25]
1. 当OSS读写权限设置为私有时，可以上传文件，但无法访问，需要通过SDK获取限时访问链接（评估一下是否有必要支持）
2. 当配置BASE_URL时，需要的格式为：https://xxxx.xxx.aliyuncs.com，请在官方插件文档中更新

**Comment by hezzze** [comment]
https://github.com/hezzze/strapi-provider-upload-oss/pull/24 已更新
